{
 "title": "Loki Logs Dashboard",
 "tags": [
  "observability",
  "logs",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Log Volume by Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({service=~\".+\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total Error Logs (Last 1h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({service=~\".+\"} |= \"error\" [1h])"
    }
   ]
  },
  {
   "title": "POST Requests (Last 1h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({service=~\".+\"} |= \"POST\" [1h])"
    }
   ]
  },
  {
   "title": "Live Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{service=~\".+\"}"
    }
   ]
  }
 ]
}